<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\src\Nodeable.Infrastructure\Nodeable.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Testcontainers.PostgreSql" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\Shared\PostgresFixture.cs" Link="PostgresFixture.cs" />
  </ItemGroup>

</Project>
