// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nodeable.Infrastructure.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Nodeable.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(NodeableDbContext))]
    [Migration("20261009113647_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pg_trgm");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Nodeable.Domain.Entities.CrawlJob", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset?>("LockedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("locked_at");

                    b.Property<string>("LockedBy")
                        .HasColumnType("text")
                        .HasColumnName("locked_by");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<DateTimeOffset>("RunAfter")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("run_after")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid>("TargetMbid")
                        .HasColumnType("uuid")
                        .HasColumnName("target_mbid");

                    b.Property<string>("Traceparent")
                        .HasColumnType("text")
                        .HasColumnName("traceparent");

                    b.HasKey("Id")
                        .HasName("pk_crawl_jobs");

                    b.HasIndex("Kind", "TargetMbid")
                        .IsUnique()
                        .HasDatabaseName("ix_crawl_jobs_kind_target_mbid")
                        .HasFilter("status IN ('pending', 'running')");

                    b.HasIndex("Priority", "RunAfter")
                        .IsDescending(true, false)
                        .HasDatabaseName("ix_crawl_jobs_priority_run_after")
                        .HasFilter("status = 'pending'");

                    b.ToTable("crawl_jobs", null, t =>
                        {
                            t.HasCheckConstraint("ck_crawl_jobs_kind", "kind IN ('recording', 'work', 'release', 'preview', 'artist')");

                            t.HasCheckConstraint("ck_crawl_jobs_status", "status IN ('pending', 'running', 'done', 'failed')");
                        });
                });

            modelBuilder.Entity("Nodeable.Domain.Entities.Credit", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Detail")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("")
                        .HasColumnName("detail");

                    b.Property<Guid>("PersonMbid")
                        .HasColumnType("uuid")
                        .HasColumnName("person_mbid");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.Property<Guid>("SubjectMbid")
                        .HasColumnType("uuid")
                        .HasColumnName("subject_mbid");

                    b.Property<string>("SubjectType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("subject_type");

                    b.HasKey("Id")
                        .HasName("pk_credits");

                    b.HasIndex("SubjectType", "SubjectMbid")
                        .HasDatabaseName("ix_credits_subject_type_subject_mbid");

                    b.HasIndex("PersonMbid", "SubjectType", "SubjectMbid", "Role", "Detail")
                        .IsUnique()
                        .HasDatabaseName("ix_credits_person_mbid_subject_type_subject_mbid_role_detail");

                    b.ToTable("credits", null, t =>
                        {
                            t.HasCheckConstraint("ck_credits_role", "role IN ('producer', 'songwriter', 'mixing', 'engineering', 'instrument', 'vocal', 'other')");

                            t.HasCheckConstraint("ck_credits_source", "source IN ('musicbrainz', 'discogs')");

                            t.HasCheckConstraint("ck_credits_subject_type", "subject_type IN ('recording', 'work', 'release')");
                        });
                });

            modelBuilder.Entity("Nodeable.Domain.Entities.Graph", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AnonTokenHash")
                        .HasColumnType("text")
                        .HasColumnName("anon_token_hash");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean")
                        .HasColumnName("is_public");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid?>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<string>("ShareSlug")
                        .HasColumnType("text")
                        .HasColumnName("share_slug");

                    b.HasKey("Id")
                        .HasName("pk_graphs");

                    b.ToTable("graphs", (string)null);
                });

            modelBuilder.Entity("Nodeable.Domain.Entities.GraphSong", b =>
                {
                    b.Property<Guid>("GraphId")
                        .HasColumnType("uuid")
                        .HasColumnName("graph_id");

                    b.Property<Guid>("RecordingMbid")
                        .HasColumnType("uuid")
                        .HasColumnName("recording_mbid");

                    b.Property<DateTimeOffset>("AddedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("added_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("GraphId", "RecordingMbid")
                        .HasName("pk_graph_songs");

                    b.HasIndex("RecordingMbid")
                        .HasDatabaseName("ix_graph_songs_recording_mbid");

                    b.ToTable("graph_songs", (string)null);
                });

            modelBuilder.Entity("Nodeable.Domain.Entities.Person", b =>
                {
                    b.Property<Guid>("Mbid")
                        .HasColumnType("uuid")
                        .HasColumnName("mbid");

                    b.Property<string>("Disambiguation")
                        .HasColumnType("text")
                        .HasColumnName("disambiguation");

                    b.Property<DateTimeOffset>("FetchedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fetched_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("SortName")
                        .HasColumnType("text")
                        .HasColumnName("sort_name");

                    b.Property<string>("Type")
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Mbid")
                        .HasName("pk_people");

                    b.ToTable("people", (string)null);
                });

            modelBuilder.Entity("Nodeable.Domain.Entities.Preview", b =>
                {
                    b.Property<Guid>("RecordingMbid")
                        .HasColumnType("uuid")
                        .HasColumnName("recording_mbid");

                    b.Property<string>("Provider")
                        .HasColumnType("text")
                        .HasColumnName("provider");

                    b.Property<DateTimeOffset>("FetchedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fetched_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("ProviderTrackId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("provider_track_id");

                    b.HasKey("RecordingMbid", "Provider")
                        .HasName("pk_previews");

                    b.ToTable("previews", null, t =>
                        {
                            t.HasCheckConstraint("ck_previews_provider", "provider IN ('deezer')");
                        });
                });

            modelBuilder.Entity("Nodeable.Domain.Entities.Recording", b =>
                {
                    b.Property<Guid>("Mbid")
                        .HasColumnType("uuid")
                        .HasColumnName("mbid");

                    b.Property<string>("ArtistCredit")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("artist_credit");

                    b.Property<string>("CreditsStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("credits_status");

                    b.Property<DateTimeOffset>("FetchedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fetched_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateOnly?>("FirstReleaseDate")
                        .HasColumnType("date")
                        .HasColumnName("first_release_date");

                    b.Property<int?>("LengthMs")
                        .HasColumnType("integer")
                        .HasColumnName("length_ms");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Mbid")
                        .HasName("pk_recordings");

                    b.HasIndex("Title")
                        .HasDatabaseName("ix_recordings_title");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Title"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Title"), new[] { "gin_trgm_ops" });

                    b.ToTable("recordings", null, t =>
                        {
                            t.HasCheckConstraint("ck_recordings_credits_status", "credits_status IN ('none', 'partial', 'complete')");
                        });
                });

            modelBuilder.Entity("Nodeable.Domain.Entities.RecordingRelease", b =>
                {
                    b.Property<Guid>("RecordingMbid")
                        .HasColumnType("uuid")
                        .HasColumnName("recording_mbid");

                    b.Property<Guid>("ReleaseMbid")
                        .HasColumnType("uuid")
                        .HasColumnName("release_mbid");

                    b.HasKey("RecordingMbid", "ReleaseMbid")
                        .HasName("pk_recording_releases");

                    b.HasIndex("ReleaseMbid")
                        .HasDatabaseName("ix_recording_releases_release_mbid");

                    b.ToTable("recording_releases", (string)null);
                });

            modelBuilder.Entity("Nodeable.Domain.Entities.RecordingWork", b =>
                {
                    b.Property<Guid>("RecordingMbid")
                        .HasColumnType("uuid")
                        .HasColumnName("recording_mbid");

                    b.Property<Guid>("WorkMbid")
                        .HasColumnType("uuid")
                        .HasColumnName("work_mbid");

                    b.HasKey("RecordingMbid", "WorkMbid")
                        .HasName("pk_recording_works");

                    b.HasIndex("WorkMbid")
                        .HasDatabaseName("ix_recording_works_work_mbid");

                    b.ToTable("recording_works", (string)null);
                });

            modelBuilder.Entity("Nodeable.Domain.Entities.Release", b =>
                {
                    b.Property<Guid>("Mbid")
                        .HasColumnType("uuid")
                        .HasColumnName("mbid");

                    b.Property<DateOnly?>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<DateTimeOffset>("FetchedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fetched_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Mbid")
                        .HasName("pk_releases");

                    b.ToTable("releases", (string)null);
                });

            modelBuilder.Entity("Nodeable.Domain.Entities.Work", b =>
                {
                    b.Property<Guid>("Mbid")
                        .HasColumnType("uuid")
                        .HasColumnName("mbid");

                    b.Property<DateTimeOffset>("FetchedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fetched_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Mbid")
                        .HasName("pk_works");

                    b.ToTable("works", (string)null);
                });

            modelBuilder.Entity("Nodeable.Domain.Entities.Credit", b =>
                {
                    b.HasOne("Nodeable.Domain.Entities.Person", null)
                        .WithMany()
                        .HasForeignKey("PersonMbid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_credits_people_person_mbid");
                });

            modelBuilder.Entity("Nodeable.Domain.Entities.GraphSong", b =>
                {
                    b.HasOne("Nodeable.Domain.Entities.Graph", null)
                        .WithMany()
                        .HasForeignKey("GraphId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_graph_songs_graphs_graph_id");

                    b.HasOne("Nodeable.Domain.Entities.Recording", null)
                        .WithMany()
                        .HasForeignKey("RecordingMbid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_graph_songs_recordings_recording_mbid");
                });

            modelBuilder.Entity("Nodeable.Domain.Entities.Preview", b =>
                {
                    b.HasOne("Nodeable.Domain.Entities.Recording", null)
                        .WithMany()
                        .HasForeignKey("RecordingMbid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_previews_recordings_recording_mbid");
                });

            modelBuilder.Entity("Nodeable.Domain.Entities.RecordingRelease", b =>
                {
                    b.HasOne("Nodeable.Domain.Entities.Recording", null)
                        .WithMany()
                        .HasForeignKey("RecordingMbid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_recording_releases_recordings_recording_mbid");

                    b.HasOne("Nodeable.Domain.Entities.Release", null)
                        .WithMany()
                        .HasForeignKey("ReleaseMbid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_recording_releases_releases_release_mbid");
                });

            modelBuilder.Entity("Nodeable.Domain.Entities.RecordingWork", b =>
                {
                    b.HasOne("Nodeable.Domain.Entities.Recording", null)
                        .WithMany()
                        .HasForeignKey("RecordingMbid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_recording_works_recordings_recording_mbid");

                    b.HasOne("Nodeable.Domain.Entities.Work", null)
                        .WithMany()
                        .HasForeignKey("WorkMbid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_recording_works_works_work_mbid");
                });
#pragma warning restore 612, 618
        }
    }
}
